flask/portfolio/bp_users/models.py
from flask_login import UserMixin
from portfolio import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    premium = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"User('{self.username}', '{self.image_file}', '{self.premium}')"


flask/portfolio/bp_filehost/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import SubmitField


class FileForm(FlaskForm):
    file = FileField('File', validators=[FileRequired(), FileAllowed(['jpg', 'png', 'mp4', 'webp', 'jpeg', 'webm'], 'File not allowed!')])
    submit = SubmitField('Submit')

flask/portfolio/bp_users/forms.py
from flask_wtf import FlaskForm
from portfolio.bp_users.models import User
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length, ValidationError


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                            validators=[DataRequired(), Length(min=2, max=20)] )
    password = PasswordField('Password',
                            validators=[DataRequired()] )
    confirm_password = PasswordField('Confirm Password',
                            validators=[DataRequired(), EqualTo('password')] )
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username already taken')
    

class LoginForm(FlaskForm):
    username = StringField('Username',
                            validators=[DataRequired(), Length(min=2, max=20)] )
    password = PasswordField('Password',
                            validators=[DataRequired()] )
    remember = BooleanField('Remember me')
    submit = SubmitField('Log in')

flask/portfolio/__init__.py
import os

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_paranoid import Paranoid
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import SCRIPTS, EXECUTABLES, UploadSet, configure_uploads, AllExcept, patch_request_class
from flask_dropzone import Dropzone


app = Flask(__name__)
if app.config["ENV"] == "production":
    app.config.from_object("config.ProductionConfig")
    paranoid = Paranoid(app)
    paranoid.redirect_view = '/'
elif app.config["ENV"] == "testing":
    app.config.from_object("config.TestingConfig")
else:
    app.config.from_object("config.DevelopmentConfig")
print(f'ENV is set to: {app.config["ENV"]}')


db = SQLAlchemy(app)

bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'bp_users.login'
login_manager.login_message_category = 'info'
login_manager.session_protection = None

filehost = UploadSet('filehost', AllExcept(SCRIPTS + EXECUTABLES))
configure_uploads(app, filehost)
patch_request_class(app, size=500*1024*1024)

dropzone = Dropzone(app)



from portfolio.bp_main.routes import bp_main

app.register_blueprint(bp_main)

from portfolio.bp_users.routes import bp_users

app.register_blueprint(bp_users)

from portfolio.bp_homescreen.routes import bp_homescreen

app.register_blueprint(bp_homescreen)

from portfolio.bp_errors.routes import bp_errors

app.register_blueprint(bp_errors)

from portfolio.bp_filehost.routes import bp_filehost

app.register_blueprint(bp_filehost)

from portfolio.bp_al.routes import bp_al

app.register_blueprint(bp_al)

flask/portfolio/bp_al/routes.py
from flask import render_template, Blueprint

bp_al = Blueprint('bp_al', __name__)

@bp_al.route('/azurlane')
def azurlane():
    return render_template('azurlane.html', title='AL')

@bp_al.route('/azurlane/submarine')
def submarine():
    return render_template('azurlane_submarine.html', title='AL Submarine Calculator')

flask/portfolio/bp_azurlane/routes.py
from flask import render_template, Blueprint

bp_azurlane = Blueprint('bp_azurlane', __name__)

@bp_azurlane.route('/azurlane')
def azurlane():
    return render_template('azurlane.html', title='Azur Lane Submarine Calculator')

flask/portfolio/bp_errors/routes.py
# Outside imports
from flask import Blueprint, render_template

bp_errors = Blueprint('bp_errors', __name__)

@bp_errors.app_errorhandler(404)
def error_404(error):
    return render_template('errors/error.html', error_message='404 not found'), 404

@bp_errors.app_errorhandler(403)
def error_403(error):
    return render_template('errors/error.html', error_message='403 forbidden'), 403

@bp_errors.app_errorhandler(500)
def error_500(error):
    return render_template('errors/error.html', error_message='500 internal server error'), 500

@bp_errors.app_errorhandler(413)
def error_413(error):
    return render_template('errors/error.html', error_message='413 payload too large'), 413

@bp_errors.app_errorhandler(400)
def error_400(error):
    return render_template('errors/error.html', error_message='400 bad request'), 400

flask/portfolio/bp_filehost/routes.py
from flask import (
    Blueprint, abort, flash, redirect, render_template, request, url_for)
from flask_login import current_user, login_required
from portfolio import filehost
from werkzeug.utils import secure_filename

bp_filehost = Blueprint('bp_filehost', __name__)


@bp_filehost.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    # Check premium
    if not current_user.premium:
        abort(403)
    if request.method == 'POST' and 'file' in request.files:
        uploaded_file = request.files['file']
        filename = filehost.resolve_conflict(filehost.config.destination, secure_filename(uploaded_file.filename))
        if filename != '':
            filehost.save(uploaded_file)
            #flash(f'File {filename} uploaded succcessfully', 'success')
        return redirect(url_for('bp_filehost.upload'))
    return render_template('upload.html', title='Upload')
    
# @bp_filehost.route('/f/<filename>')
# def view_upload(filename):
#     return send_from_directory(os.path.basename(current_app.config['UPLOADED_FILEHOST_DEST']), filename)

flask/portfolio/bp_homescreen/routes.py
# Outside imports
from flask          import Blueprint, render_template
from flask_login    import login_required

bp_homescreen = Blueprint('bp_homescreen', __name__)

@bp_homescreen.route("/homescreen")
@login_required
def homescreen():
    return render_template('homescreen.html', title='Homescreen')

flask/portfolio/bp_main/routes.py
# Outside imports
from flask import Blueprint, render_template

bp_main = Blueprint('bp_main', __name__)


@bp_main.route("/")
@bp_main.route("/home")
def home():
    return render_template('home.html', title='Home')

@bp_main.route("/about")
def about():
    return render_template('about.html', title='About')

flask/portfolio/bp_users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from portfolio import bcrypt, db
from portfolio.bp_users.forms import LoginForm, RegistrationForm
from portfolio.bp_users.models import User

bp_users = Blueprint('bp_users', __name__)

@bp_users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('bp_users.login'))
    return render_template('register.html', form=form, title='Register')

@bp_users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('bp_main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('bp_main.home'))
        else:
            flash('Login unsuccessful', 'danger')
    return render_template('login.html', form=form, title='Login')


@bp_users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('bp_main.home'))

@bp_users.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account')

@bp_users.route("/premium")
@login_required
def get_premium():
    user = current_user
    user.premium = True
    db.session.add(user)
    db.session.commit()
    flash(f'Congratulations, {current_user.username}!', 'success')
    return redirect(url_for('bp_users.login'))

flask/portfolio/templates/about.html
{% extends "index.html" %}
{% block content %}

<div class='content-section'>
  <div class="row">
    <div class="col" id="README"></div>
  </div>
  <div class="row">
    <div class="col">
      Source code at <a href="https://github.com/viperML/flaskapp">GitHub</a>
    </div>
  </div>
</div>


{% endblock content %}

flask/portfolio/templates/account.html
{% extends "index.html" %}
{% block content %}
    <h1> {{ current_user.username }} </h1>
{% endblock content %}

flask/portfolio/templates/azurlane.html
{% extends "index.html" %}
{% block content %}

<div class='content-section'>
    <h1><a href="{{ url_for('bp_al.submarine') }}">Submarine Calculator</a></h1>
</div>

{% endblock content %}

flask/portfolio/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    

    <!-- Common CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">

    <!-- Favicon and title -->
    <title>🐍.☕ - {{ title }}</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
	  <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-96x96.png') }}">
    <script type="text/javascript" src="{{url_for('static', filename='dist/main.js')}}"></script>

    <!-- Vue.js -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.x"></script> -->
    

    {% block head %}{% endblock head %}
  </head>


  <body>

    <header class="site-header">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top scrolling-navbar">
        <div class="container">
          <img src="{{ url_for('static', filename='img/test_down.png')}}" class="img-fluid mx-3 navbar-brand" width="30">
          <a class="navbar-brand mr-4" href="{{ url_for('bp_main.home') }}">viper.cafe</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('bp_main.about') }}">About</a>
              <a class="nav-item nav-link" href="/f">File Host</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if current_user.premium %}
                  <a class="nav-item nav-link" href="{{ url_for('bp_filehost.upload') }}">Upload</a>
                  <a class="nav-item nav-link" href="{{ url_for('bp_homescreen.homescreen') }}">Homescreen</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('bp_users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('bp_users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      {% block header %}{% endblock header %}

    </header>
    
    
    <div class='container'>
      <!-- Flash message -->
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <!-- Main Content -->
      {% block content %}{% endblock content %}
    </div>
    
    <!-- JavaScript -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

  </body>
  

</html>

flask/portfolio/templates/home.html
{% extends "index.html" %}
{% block content %}

<div class='content-section' id="app">
    <h1>Home</h1>
</div>


{% endblock content %}

flask/portfolio/templates/homescreen.html
{% extends "index.html" %}
{% block content %}
    
    <div class="row" style="background-color: yellow;">
        <h1>Homescreeen</h1>
    </div>
    <div class="row" style="background-color: red;">
        <div class="col">
          One of three columns
        </div>
        <div class="col">
          One of three columns
        </div>
        <div class="col">
          One of three columns
        </div>
      </div>
{% endblock content %}

flask/portfolio/templates/index.html
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <!-- Common CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}">

    <!-- Favicon and title -->
    <title>🐍.☕ - {{ title }}</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
	  <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-96x96.png') }}">
    <script type="text/javascript" src="{{url_for('static', filename='dist/main.js')}}"></script>

    <!-- Flask Head extension-->
    {% block head %}{% endblock head %}
  </head>


  <body>

    <header class="site-header">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top scrolling-navbar">
        <div class="container">
          <img src="{{ url_for('static', filename='img/test_down.png')}}" class="img-fluid mx-3 navbar-brand" width="30">
          <a class="navbar-brand mr-4" href="{{ url_for('bp_main.home') }}">viper.cafe</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('bp_main.about') }}">About</a>
              <a class="nav-item nav-link" href="/f">File Host</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                {% if current_user.premium %}
                  <a class="nav-item nav-link" href="{{ url_for('bp_filehost.upload') }}">Upload</a>
                  <a class="nav-item nav-link" href="{{ url_for('bp_homescreen.homescreen') }}">Homescreen</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('bp_users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('bp_users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('bp_users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      {% block header %}{% endblock header %}

    </header>
    
    
    <div class='container'>
      <!-- Flash message -->
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <!-- Main Content -->
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

flask/portfolio/templates/login.html
{% extends "index.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Register <a class="ml-2" href="{{ url_for('bp_users.register') }}">here</a>
        </small>
    </div>
{% endblock content %}

flask/portfolio/templates/register.html
{% extends "index.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register an account</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label")}}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span> {{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Login <a class="ml-2" href="{{ url_for('bp_users.login') }}">here</a>
        </small>
    </div>
{% endblock content %}

flask/portfolio/templates/upload.html
{% extends "index.html" %}
{% block head %}
{{ dropzone.load_css() }}
{% endblock head %}


{% block content %}

    <div class="content-section">
        <h1>File Upload</h1>
        {{ dropzone.create(action=url_for('bp_filehost.upload') ) }}
        {{ dropzone.load_js() }}
        {{ dropzone.config() }}
    </div>

{% endblock content %}